import argparse
import pathlib

KEY = "STABLE_VOYAGE_COMMIT"
FALLBACK = "unstamped"


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def read_commit(path: pathlib.Path) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return FALLBACK
    for raw_line in text.splitlines():
        name, _, value = raw_line.strip().partition(" ")
        if name == KEY and value:
            return value
    return FALLBACK


def render(commit: str) -> str:
    return (
        "// Generated by bazel/generate_version.py -- do not edit.\n"
        '#include "src/diagnostics/version.hpp"\n'
        "\n"
        "namespace voyage::version {\n"
        "\n"
        "const char *commit() {\n"
        "    return %s;\n"
        "}\n"
        "\n"
        "}  // namespace voyage::version\n" % cpp_string(commit)
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--status", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    commit = read_commit(pathlib.Path(args.status))
    pathlib.Path(args.output).write_text(render(commit), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
